# Generated by Django 5.0.6 on 2024-06-30 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0007_review_edit_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="edit_count",
        ),
    ]
