# Generated by Django 5.0.6 on 2024-07-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0008_remove_review_edit_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
